// app/layout.js
import { ClerkProvider } from '@clerk/nextjs';
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <title>Learn Minimal</title>
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body
          className="bg-cover bg-center"
          style={{ backgroundImage: "url('/background.jpg')" }}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
